modLoader="lowcodefml"
loaderVersion="[46,]"
license="None"

[[mods]]
modId="create_mortar"
version="0.2.2"
displayname="Create: Mortar"
description="Recipe changes and create add on compat"
dependencies="AFTER:*"
logoFile = "Mortar.png"

[[dependencies.create_mortar]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.create_mortar]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="tfmg"
mandatory= false
versionRange="[0.8.0b,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="railways"
mandatory= false
versionRange="[1.6.1+forge-mc1.20.1,)"
ordering="AFTER"
side="BOTH"


[[dependencies.create_mortar]]
modId="createbigcannons"
mandatory= false
versionRange="[0.5.3.b,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="create_dd"
mandatory= false
versionRange="[0.2c,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="design_decor"
mandatory= false
versionRange="[0.4.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="createaddition"
mandatory= false
versionRange="[1.2.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="molten_metals"
mandatory= false
versionRange="[0.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_mortar]]
modId="createdieselgenerators"
mandatory= false
versionRange="[1.20.1-1.1,)"
ordering="AFTER"
side="BOTH"